IF(CXSPARSE_LIBRARY AND CXSPARSE_INCLUDE_DIR)
  SET(CXSPARSE_FOUND TRUE)
ELSE(CXSPARSE_LIBRARY AND CXSPARSE_INCLUDE_DIR)
  FIND_PATH(CXSPARSE_INCLUDE_DIR cs.h
    /usr/include/suitesparse
    /usr/local/include
    )
  FIND_LIBRARY(CXSPARSE_LIBRARY NAMES cxsparse
    /usr/lib
    /usr/local/lib
  )

  IF(CXSPARSE_LIBRARY AND CXSPARSE_INCLUDE_DIR)
    SET(CXSPARSE_FOUND TRUE)
  ENDIF(CXSPARSE_LIBRARY AND CXSPARSE_INCLUDE_DIR)

ENDIF(CXSPARSE_LIBRARY AND CXSPARSE_INCLUDE_DIR)

IF(CXSPARSE_FOUND)
  IF (NOT CXSparse_FIND_QUIETLY)
      MESSAGE(STATUS "Found CXSparse: ${CXSPARSE_LIBRARY}")
   ENDIF (NOT CXSparse_FIND_QUIETLY)
ELSE (CXSPARSE_FOUND)
   IF (CXSparse_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find CXSparse")
   ENDIF (CXSparse_FIND_REQUIRED)
ENDIF (CXSPARSE_FOUND)
